const Errors = {
    AGENT_WALLET_NOT_INIT: 'AGENT_WALLET_NOT_INIT',
    SELECTED_ASSET_NOT_INIT: 'SELECTED_ASSET_NOT_INIT',
    ASSET_LEVERAGE_DATA_NOT_INIT: 'ASSET_LEVERAGE_DATA_NOT_INIT',
    ASSET_ID_NOT_FOUND: 'ASSET_ID_NOT_FOUND',
    SZ_DECIMALS_NOT_FOUND: 'SZ_DECIMALS_NOT_FOUND',
}

export default Errors
